version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
