require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/DescribeClass:
  Exclude:
    - spec/requests/*

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Metrics/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
