require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/DescribeClass:
  Exclude:
    - spec/requests/*

RSpec/ExampleLength:
  Max: 10

Metrics/BlockLength:
  ExcludedMethods:
    - describe

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Layout/DotPosition:
  EnforcedStyle: trailing
