version: 2.1

orbs:
  ruby: circleci/ruby@2.1.2

executors:
  ruby:
    docker:
      - image: cimg/ruby:3.3.0

jobs:
  build:
    executor: ruby
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: |
            git --no-pager diff HEAD
            git status
            test -z "$(git status --porcelain)"
      - ruby/rubocop-check
      - ruby/rspec-test

  publish:
    executor: ruby
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: gem build
      - run:
          command: gem push zengin_code_rails-*.gem

workflows:
  version: 2
  default:
    jobs:
      - build
      - publish:
          filters:
            tags:
              only: /^v(\d+).(\d+).(\d+)$/
            branches:
              ignore: /.*/
