version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundler-v1567765223
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install
      - save_cache:
          key: bundler-v1567765223
          paths:
            - vendor/bundle
      - ruby/rubocop-check
      - ruby/rspec-test
