version: 2.1

orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: |
            git --no-pager diff HEAD
            git status
            test -z "$(git status --porcelain)"
      - ruby/rubocop-check
      - ruby/rspec-test

  publish:
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: gem build
      - run:
          command: gem push zengin_code_rails-*.gem

workflows:
  version: 2
  default:
    jobs:
      - build
      - publish:
          filters:
            tags:
              only: /^v(\d).(\d).(\d)$/
            branches:
              ignore: /.*/
