version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: |
            git --no-pager diff HEAD
            git status
            test -z "$(git status --porcelain)"
      - ruby/rubocop-check
      - ruby/rspec-test
