name: Auto Merge Dependabot

on:
  pull_request:
    branches:
      - master

jobs:
  auto_merge_dependabot:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.5.4
        with:
          github-token: ${{ github.token }}
          use-github-auto-merge: true
